import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
/* import ManualHeader from '../components/ManualHeader' */
import Header from '../components/Header'
import RaffleEntrance from '../components/RaffleEntrance'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Decentralized Raffle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <RaffleEntrance></RaffleEntrance>
    </div>
  )
}
